version: "3"
services:
    web:
        container_name: "water-nginx"
        image: nginx:latest
        ports:
            - "4000-5000:4000-5000"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
            - ./php-location.conf:/etc/nginx/shared/php-location.conf
            - ${PROJECTS_DIRECTORY}:/projects
    php:
        container_name: "water-php"
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ${PROJECTS_DIRECTORY}:/projects
